/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelesPrincipales;

import control.EstadisticasExcel;
import control.ImageLoader;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author gaspa
 */
public final class PanelResultados extends javax.swing.JPanel {

    public static PanelResultados instancia;

    /**
     * Creates new form PanelResultados
     */
    public PanelResultados() {
        initComponents();
        guardarEstadisticas();
        establecerDineroGanado();
    }

    public static PanelResultados getInstance() {
        if (instancia == null) {
            instancia = new PanelResultados();
        }
        return instancia;
    }
    
    public void establecerDineroGanado(){
        double dinero = ImageLoader.obtenerValorTotalUsado();
        dineroGanadoLabel.setText(String.valueOf(dinero));
    }

    public void guardarEstadisticas() {
        // Se guarda en la carpeta de documentos
        String userHome = System.getProperty("user.home");
        String documentosPath = userHome + File.separator + "Documents";

        // archivo con fecha y hora
        String timestamp = new SimpleDateFormat("yyyy-MM-dd_HH-mm-ss").format(new Date());
        String nombreArchivo = documentosPath + File.separator + "estadisticas_" + timestamp + ".xlsx";

        EstadisticasExcel.getInstance().exportarAExcel(nombreArchivo);

        System.out.println("Estadísticas guardadas en: " + nombreArchivo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dineroGanadoLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("RESULTADOS ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Dinero ganado:");

        dineroGanadoLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        dineroGanadoLabel.setText("---");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(882, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dineroGanadoLabel))
                    .addComponent(jLabel2))
                .addGap(814, 814, 814))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(269, 269, 269)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dineroGanadoLabel))
                .addContainerGap(731, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dineroGanadoLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
