/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelesPrincipales;

import control.Navegacion;
import control.Temporizador;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.SwingConstants;

/**
 *
 * @author Ilian Fernando Gastelum Romo
 */
public class RatePanel extends javax.swing.JPanel {
    public static RatePanel instancia;
    private JRadioButton[] botones;
    private ButtonGroup grupoBotones;
    private JPanel botonesPanel;
    private int valorSeleccionado = -1;
    /**
     * Creates new form ratePanel
     */
    public RatePanel() {
        initComponents();
        this.setLayout(new GridLayout(2, 1, 10, 1));
        setearTextoYBotonesCentral();
    }
    public static RatePanel getInstance(){
        if (instancia == null) {
            instancia = new RatePanel();
        }
        return instancia;
    }
    public void setearTextoYBotonesCentral() {
        if (botonesPanel != null) return;

        JLabel preguntaLabel = new JLabel("¿Qué tanto disfrutaste la recompensa?", SwingConstants.CENTER);
        preguntaLabel.setFont(new java.awt.Font("Segoe UI", 0, 48));
        this.add(preguntaLabel);

        grupoBotones = new ButtonGroup();
        botonesPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 10, 5));
        botones = new JRadioButton[9];

        for (int i = 0; i < 9; i++) {
            final int valor = i + 1;
            JRadioButton boton = new JRadioButton(String.valueOf(valor));
            boton.setFont(new java.awt.Font("Arial", Font.PLAIN, 18));
            boton.addActionListener(e -> valorSeleccionado = valor); 
            grupoBotones.add(boton);
            botonesPanel.add(boton);
            botones[i] = boton;
        }

        this.add(botonesPanel);
    }
    public void limpiarSeleccion() {
        if (grupoBotones != null) {
            grupoBotones.clearSelection();
        }
    }
    public void siguientePantalla(){
        Temporizador.temporizador(2500, () -> {
            Navegacion.getInstance().mostrarCuePanel();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
